/* 1번 */
SELECT ANIMAL_TYPE, COUNT(*) 
FROM ANIMAL_INS 
GROUP BY ANIMAL_TYPE 
ORDER BY ANIMAL_TYPE;

/* 2번 */
SELECT NAME, COUNT(*)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(*) > 1
ORDER BY NAME;

/* 3번 */
SELECT HOUR(DATETIME), COUNT(*)
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);

/* 4번 */
WITH RECURSIVE TIME AS
(
SELECT 0 AS HOURS
UNION ALL
SELECT HOURS + 1 FROM TIME WHERE HOURS < 23
)
SELECT T.HOURS, COUNT(A.ANIMAL_ID)
FROM ANIMAL_OUTS A RIGHT OUTER JOIN TIME T
ON HOUR(A.DATETIME) = T.HOURS
GROUP BY T.HOURS;

