/* 1¹ø */
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NULL;

/* 2¹ø */
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NOT NULL;

/* 3¹ø */
SELECT ANIMAL_TYPE, IFNULL(NAME, "No name"), SEX_UPON_INTAKE FROM ANIMAL_INS;


