/* 1번 */
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME DESC LIMIT 1;

/* 2번 */
SELECT MIN(DATETIME) FROM ANIMAL_INS;

/* 3번 */
SELECT COUNT(ANIMAL_ID) FROM ANIMAL_INS;

/* 4번 */
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS WHERE NAME IS NOT NULL;

